kind: Deployment
apiVersion: apps/v1
metadata:
  name: driver-service-{{ .Values.versionName }}
  labels:
    app: driver-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
        version: {{ .Values.version }}
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: driver-service
          image: quay.io/jamjones/courie-driver:{{ default "latest" .Values.dockerTag }}
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: driver-service
          imagePullPolicy: Always
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%