{{- if .Values.firstInstall -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: driver-service-routing-config
spec:
  hosts:
  - "driver-api.{{ .Values.baseOpenshiftAppHostname }}"
  gateways:
  - driver-service-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: driver-service
        subset: {{ .Values.versionName }}
{{- end }}